# Generated by Django 4.1.7 on 2023-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("accounts", "0003_remove_user_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="products",
            field=models.ManyToManyField(to="shop.product"),
        ),
    ]
