# Generated by Django 4.1.7 on 2023-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
