# Generated by Django 4.1.7 on 2023-02-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_otpcode_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="products",
        ),
    ]
