# Generated by Django 4.1.7 on 2023-04-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_pendingsale"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingSale",
        ),
    ]
