# Generated by Django 4.1.7 on 2023-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_userproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
