# Generated by Django 4.1.7 on 2023-02-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_userproduct_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="users",
        ),
    ]
