# Generated by Django 4.1.7 on 2023-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_pricechange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproduct",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="pricechange",
            name="new_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="pricechange",
            name="old_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
