# Generated by Django 4.1.7 on 2023-02-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rename_date_added_userproduct_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproduct",
            old_name="created_at",
            new_name="date_added",
        ),
    ]
