# Generated by Django 4.1.7 on 2023-02-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rename_created_at_userproduct_date_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproduct",
            old_name="date_added",
            new_name="created_at",
        ),
    ]
