# Generated by Django 4.1.7 on 2023-02-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_seller_sale_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
