# Generated by Django 4.1.7 on 2023-02-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
