# Generated by Django 4.1.7 on 2023-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_sale_buyer_remove_sale_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="is_for_sale",
            field=models.BooleanField(default=True),
        ),
    ]
