# Generated by Django 4.1.7 on 2023-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_userproduct_is_for_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="initial_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
