# Generated by Django 4.1.7 on 2023-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_userproduct_initial_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="initial_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
