# Generated by Django 4.1.7 on 2023-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_userproduct_initial_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="is_for_sale",
            field=models.BooleanField(default=False),
        ),
    ]
