# Generated by Django 4.1.7 on 2023-02-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_alter_userproduct_initial_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechange",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_changes",
                to="shop.product",
            ),
        ),
    ]
