# Generated by Django 4.1.7 on 2023-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_pricechange_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="price_changes",
            field=models.ManyToManyField(blank=True, to="shop.pricechange"),
        ),
    ]
