# Generated by Django 4.1.7 on 2023-03-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_remove_userproduct_price_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_history",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="shop.pricechange"
            ),
        ),
        migrations.AlterField(
            model_name="pricechange",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
    ]
