# Generated by Django 4.1.7 on 2023-04-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_productlisting_buyrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlisting",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productlisting",
            name="user",
        ),
        migrations.DeleteModel(
            name="BuyRequest",
        ),
        migrations.DeleteModel(
            name="ProductListing",
        ),
    ]
